import os
import httpx
import logging

logger = logging.getLogger(__name__)

ADMIN_EMAIL = os.getenv("ADMIN_EMAIL", "growix299@gmail.com")

def get_resend_key():
    k = os.getenv("RESEND_API_KEY")
    if k:
        return k.strip().strip("'").strip('"')
    return None

async def send_delivery_email(to_email: str, product_name: str, order_id: str) -> bool:
    """
    Sends a confirmation email to the user when they buy an OTT product.
    Since domain verification is pending, it sends via onboarding@resend.dev.
    """
    api_key = get_resend_key()
    if not api_key:
        logger.error("RESEND_API_KEY environment variable is not set.")
        return False

    url = "https://api.resend.com/emails"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    # Now using the verified custom domain for sending emails to any customer
    payload = {
        "from": "support@nexatutomate.shop",
        "to": to_email,
        "subject": f"OTT Activation Request - {product_name}",
        "html": f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; background-color: #0d0e12; color: #fff;">
            <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #38bdf8; font-weight: bold; font-family: 'Poppins', sans-serif;">OTT ACTIVATION IN PROGRESS</h1>
                <p style="color: #9ca3af; font-size: 14px;">Order ID: {order_id}</p>
            </div>
            <div style="background-color: #1e293b; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
                <h3 style="margin-top: 0; color: #fff;">Order Details:</h3>
                <p style="margin: 5px 0;"><strong>Product:</strong> {product_name}</p>
                <p style="margin: 5px 0;"><strong>Status:</strong> Processing</p>
                <p style="margin: 5px 0;"><strong>Delivery Type:</strong> Manual Activation</p>
            </div>
            <p style="font-size: 15px; line-height: 1.5; color: #d1d5db;">
                Thank you for your purchase! Our team is activating your <strong>{product_name}</strong> account. 
                You will receive another update on Telegram or via email as soon as it is active.
            </p>
            <hr style="border-color: #334155; margin: 20px 0;">
            <p style="font-size: 12px; color: #6b7280; text-align: center;">
                This email was automatically generated by TG Bot Delivery System.
            </p>
        </div>
        """
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(url, headers=headers, json=payload, timeout=10.0)
            if response.status_code in (200, 201):
                logger.info(f"Email sent successfully to {to_email}")
                return True
            else:
                err_msg = f"Resend API Error: {response.status_code} - {response.text}"
                logger.error(err_msg)
                raise Exception(err_msg)
    except Exception as e:
        logger.error(f"Exception raised while sending email: {str(e)}")
        raise e


async def send_credential_email(to_email: str, product_name: str, order_id: str, username: str, password: str) -> bool:
    """
    Sends OTT credentials directly to the customer via email after auto-delivery.
    """
    api_key = get_resend_key()
    if not api_key:
        logger.error("RESEND_API_KEY environment variable is not set.")
        return False

    url = "https://api.resend.com/emails"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "from": "support@nexatutomate.shop",
        "to": to_email,
        "subject": f"✅ Your {product_name} Credentials - OTT ACTIVATION!",
        "html": f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; background-color: #0d0e12; color: #fff;">
            <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #22c55e; font-weight: bold;">✅ OTT ACTIVATION!</h1>
                <p style="color: #9ca3af; font-size: 14px;">Order ID: {order_id}</p>
            </div>
            <div style="background-color: #1e293b; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
                <h3 style="margin-top: 0; color: #fff;">Your {product_name} Credentials:</h3>
                <p style="margin: 8px 0;"><strong>👤 Username/Email:</strong> <code style="background: #334155; padding: 2px 6px; border-radius: 4px;">{username}</code></p>
                <p style="margin: 8px 0;"><strong>🔒 Password:</strong> <code style="background: #334155; padding: 2px 6px; border-radius: 4px;">{password}</code></p>
            </div>
            <p style="font-size: 15px; line-height: 1.5; color: #d1d5db;">
                Your <strong>{product_name}</strong> account is ready! Please log in and change your password immediately to secure your account.
            </p>
            <hr style="border-color: #334155; margin: 20px 0;">
            <p style="font-size: 12px; color: #6b7280; text-align: center;">
                This email was automatically generated by TG Bot Delivery System.
            </p>
        </div>
        """
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(url, headers=headers, json=payload, timeout=10.0)
            if response.status_code in (200, 201):
                logger.info(f"Credential email sent successfully to {to_email}")
                return True
            else:
                err_msg = f"Resend API Error: {response.status_code} - {response.text}"
                logger.error(err_msg)
                raise Exception(err_msg)
    except Exception as e:
        logger.error(f"Exception sending credential email: {str(e)}")
        raise e


async def send_game_credential_email(to_email: str, product_name: str, order_id: str, username: str, password: str, subscription_info: str = "") -> bool:
    """
    Sends game login credentials to the customer via email after automated delivery.
    """
    api_key = get_resend_key()
    if not api_key:
        logger.error("RESEND_API_KEY environment variable is not set.")
        return False

    url = "https://api.resend.com/emails"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "from": "support@nexatutomate.shop",
        "to": to_email,
        "subject": f"✨ Your {product_name} Login Credentials",
        "html": f"""
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px; background-color: #0d0e12; color: #fff;">
            <div style="text-align: center; margin-bottom: 20px;">
                <h1 style="color: #3b82f6; font-weight: bold;">🎉 ACCOUNT READY!</h1>
                <p style="color: #9ca3af; font-size: 14px;">Order ID: {order_id}</p>
            </div>
            <div style="background-color: #1e293b; padding: 15px; border-radius: 6px; margin-bottom: 20px;">
                <h3 style="margin-top: 0; color: #fff;">Your {product_name} Login Credentials:</h3>
                <p style="margin: 8px 0;"><strong>👤 Username/Email:</strong> <code style="background: #334155; padding: 2px 6px; border-radius: 4px;">{username}</code></p>
                <p style="margin: 8px 0;"><strong>🔒 Password:</strong> <code style="background: #334155; padding: 2px 6px; border-radius: 4px;">{password}</code></p>
                {f'<p style="margin: 8px 0; color: #38bdf8;"><strong>⏳ {subscription_info}</strong></p>' if subscription_info else ''}
            </div>
            <p style="font-size: 15px; line-height: 1.5; color: #d1d5db;">
                Your <strong>{product_name}</strong> account is ready! Please log in and change your password immediately to secure your account. Enjoy your premium experience! ✨
            </p>
            <hr style="border-color: #334155; margin: 20px 0;">
            <p style="font-size: 12px; color: #6b7280; text-align: center;">
                This email was automatically generated by TG Bot Delivery System.
            </p>
        </div>
        """
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(url, headers=headers, json=payload, timeout=10.0)
            if response.status_code in (200, 201):
                logger.info(f"Game credential email sent successfully to {to_email}")
                return True
            else:
                err_msg = f"Resend API Error: {response.status_code} - {response.text}"
                logger.error(err_msg)
                raise Exception(err_msg)
    except Exception as e:
        logger.error(f"Exception sending game credential email: {str(e)}")
        raise e
